#!/bin/bash

#clone into applications
cd /applications/
unset GIT_DIR
rm -rf nutrition-facts-service
git clone /applications/nutrition-facts-service.git
echo '✓ Cloned repository'

#install dependencies
cd /applications/nutrition-facts-service
mvn clean package
echo '✓ Installed maven dependencies'

#move server deployment scrips and make executable
cp /applications/nutrition-facts-service/deployment/server.sh /deployment/nutrition-facts-service/server.sh
chmod 744 /deployment/nutrition-facts-service/server.sh
echo '✓ Moved deployment scripts to deployment directory'

#create and start server script
cp /applications/nutrition-facts-service/deployment/nutrition-facts-service.service /etc/systemd/system/nutrition-facts-service.service
systemctl daemon-reload
systemctl stop nutrition-facts-service
systemctl start nutrition-facts-service
systemctl enable nutrition-facts-service
echo '✓ Started server script'

#success messages
figlet nutrition-facts-service
echo '✓ SUCCESS'
